version: '3'
services:
  # db:
  #   image: mafs/oracledb:web_ca-db
  #   ports:
  #     - 1521:1521

  db:
    image: mafs/oracledb:web_ca-19.3.0-se2
    ports:
      - 1531:1521

  oracleex:
    build:
      context: .
      dockerfile: Dockerfile.19c
    image: mafs/oracleex:oralce-19c
    volumes:
      - ${WORKSPACE}/oracleex/:/app
    environment:
      - ORACLE_DSN=OracleODBC-19
      - ORACLE_SERVICE=db
      - ORACLE_USR=web_ca
      - ORACLE_PWD=bitsandbobs
    depends_on:
      - db
