version: '2'
services:
  db:
    image: mafs/oracledb:web_ca-db
    ports:
      - 1521:1521

  oracleex:
    build: .
    volumes:
      - ${WORKSPACE}/oracleex/:/app
    environment:
      - ORACLE_DSN=OracleODBC-12c
      - ORACLE_SERVICE=db
      - ORACLE_USR=web_ca
      - ORACLE_PWD=bitsandbobs
    depends_on:
      - db
